MvcProjeKampi/Controllers/ChartController.cs
using DataAccessLayer.Concrete;
using MvcProjeKampi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class ChartController : Controller
    {
        // GET: Chart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CategoryChart() //PIE
        {
            return Json(BlogList(),JsonRequestBehavior.AllowGet);
        }

        public List<CategoryClass> BlogList()
        {
            List<CategoryClass> ct = new List<CategoryClass>();
            ct.Add(new CategoryClass()
            {
                CategoryName = "Yazılım",
                CategoryCount = 8
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Seyahat",
                CategoryCount = 4
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Teknoloji",
                CategoryCount = 5
            });
            ct.Add(new CategoryClass()
            {
                CategoryName = "Spor",
                CategoryCount = 6
            });
            return ct;
        }
       
        public ActionResult WriterChart() //PIE
        {
            return View();
        }

        public List<WriterClass> WriterList()
        {
            List<WriterClass> writerClasses = new List<WriterClass>();
            using (var context = new Context())
            {
                writerClasses = context.Writers.Select(c => new WriterClass
                {
                    WriterNickname = c.WriterNickname,
                    WriterCount = c.Headings.Count()
                }).ToList();
            }

            return writerClasses;
        }

        public ActionResult WriterClass()
        {
            return Json(WriterList(), JsonRequestBehavior.AllowGet);
        }

        #region Baslik  Icerik Sayisi Listesi Grafigi

        public ActionResult HeadingListChart()
        {
            return View();
        }
      
        public List<HeadingClass> HeadingList()
        {
            List<HeadingClass> headingClasses = new List<HeadingClass>();
            using (var context = new Context())
            {
                headingClasses = context.Headings.Select(x => new HeadingClass
                {
                    HeadingName = x.HeadingName,
                    HeadingCount = x.Contents.Count()
                }).ToList();
            }

            return headingClasses;
        }

        public ActionResult HeadingListClass()
        {
            return Json(HeadingList(), JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Kategori  Icerik Sayisi Listesi Grafigi

        public ActionResult CategoryListChart()
        {
            return View();
        }

        public List<CategoryClass> CategoryList()
        {
            List<CategoryClass> categoryClasses = new List<CategoryClass>();
            using (var context = new Context())
            {
                categoryClasses = context.Categories.Select(x => new CategoryClass
                {
                    CategoryName = x.CategoryName,
                    CategoryCount = x.Headings.Count()
                }
                ).ToList();
            }
            return categoryClasses;
        }

        public ActionResult CategoryListClass()
        {
            return Json(CategoryList(), JsonRequestBehavior.AllowGet);
        }

        #endregion


    }
}

MvcProjeKampi/Views/Chart/CategoryListChart.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryListClass", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', 'CategoryCount');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Kategori - Başlık grafiği",
                width: 1600,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/HeadingListChart.cshtml
@{
    ViewBag.Title = "WriterListChart";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("HeadingListClass", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'HeadingName');
            data.addColumn('number', 'HeadingCount');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.HeadingName, obj.HeadingCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Başlık - İçerik Grafiği",
                width: 1600,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.LineChart(document
                .getElementById('Piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("CategoryChart", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'CategoryName');
            data.addColumn('number', 'CategoryCount');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.CategoryName, obj.CategoryCount]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Kategori - Başlık grafiği",
                width: 1600,
                height: 800,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

MvcProjeKampi/Views/Chart/WriterChart.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("WriterClass", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });
        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'WriterNickname');
            data.addColumn('number', 'WriterCount');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.WriterNickname, obj.WriterCount]);
            });
            data.addRows(dataArray);
            var columnChartOptions = {
                title: "Yazar-Başlık Grafiği",
                width: 1600,
                height: 800,
                bar: { groupWidth: "20%" },
            };
            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('Piechart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>